//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NastyMod.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.13.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool playerGodMode {
            get {
                return ((bool)(this["playerGodMode"]));
            }
            set {
                this["playerGodMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool playerInfiniteEnergy {
            get {
                return ((bool)(this["playerInfiniteEnergy"]));
            }
            set {
                this["playerInfiniteEnergy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool playerInfiniteStamina {
            get {
                return ((bool)(this["playerInfiniteStamina"]));
            }
            set {
                this["playerInfiniteStamina"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool playerNeverWanted {
            get {
                return ((bool)(this["playerNeverWanted"]));
            }
            set {
                this["playerNeverWanted"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float playerMoveSpeedMultiplier {
            get {
                return ((float)(this["playerMoveSpeedMultiplier"]));
            }
            set {
                this["playerMoveSpeedMultiplier"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.6")]
        public float playerCrouchSpeedMultiplier {
            get {
                return ((float)(this["playerCrouchSpeedMultiplier"]));
            }
            set {
                this["playerCrouchSpeedMultiplier"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float playerJumpMultiplier {
            get {
                return ((float)(this["playerJumpMultiplier"]));
            }
            set {
                this["playerJumpMultiplier"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool worldNpcEsp {
            get {
                return ((bool)(this["worldNpcEsp"]));
            }
            set {
                this["worldNpcEsp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool worldPlayerEsp {
            get {
                return ((bool)(this["worldPlayerEsp"]));
            }
            set {
                this["worldPlayerEsp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public float worldEspRange {
            get {
                return ((float)(this["worldEspRange"]));
            }
            set {
                this["worldEspRange"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float worldGrowSpeedMultiplier {
            get {
                return ((float)(this["worldGrowSpeedMultiplier"]));
            }
            set {
                this["worldGrowSpeedMultiplier"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string spawnerSelectedCategory {
            get {
                return ((string)(this["spawnerSelectedCategory"]));
            }
            set {
                this["spawnerSelectedCategory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int spawnerItemAmount {
            get {
                return ((int)(this["spawnerItemAmount"]));
            }
            set {
                this["spawnerItemAmount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int stackSize {
            get {
                return ((int)(this["stackSize"]));
            }
            set {
                this["stackSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool useDealSuccessChange {
            get {
                return ((bool)(this["useDealSuccessChange"]));
            }
            set {
                this["useDealSuccessChange"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.75")]
        public float dealSuccessChance {
            get {
                return ((float)(this["dealSuccessChance"]));
            }
            set {
                this["dealSuccessChance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int grabberCapacity {
            get {
                return ((int)(this["grabberCapacity"]));
            }
            set {
                this["grabberCapacity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string employeesSelectedProperty {
            get {
                return ((string)(this["employeesSelectedProperty"]));
            }
            set {
                this["employeesSelectedProperty"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string teleportSelectedCategory {
            get {
                return ((string)(this["teleportSelectedCategory"]));
            }
            set {
                this["teleportSelectedCategory"] = value;
            }
        }
    }
}
